package com.example.ebook

val column1Books = listOf(
    Book(
        title = "Front",
        frontCover = R.drawable.front_cover,
        backCover = R.drawable.back_cover,
        spineCover = R.drawable.spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Law of Human Nature",
        frontCover = R.drawable.the_law_of_human_nature_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Mountain Is You",
        frontCover = R.drawable.the_mountain_is_you_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Picture of Dorian Gray",
        frontCover = R.drawable.the_picture_of_dorian_gray_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Without a Trace",
        frontCover = R.drawable.without_a_trace_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Think and Grow Rich",
        frontCover = R.drawable.think_and_grow_rich_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 1
    ),
    Book(
        title = "Ganbatte!",
        frontCover = R.drawable.ganbatte_front_cover,
        backCover = R.drawable.ganbatte_back_cover,
        spineCover = R.drawable.ganbatte_spine_cover,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 2
    ),
    Book(
        title = "Kitchen",
        frontCover = R.drawable.kitchen_front_cover,
        backCover = R.drawable.kitchen_back_cover,
        spineCover = R.drawable.kitchen_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 3
    ),
    Book(
        title = "Las Muñecas Chinas",
        frontCover = R.drawable.las_munecas_chinas_front_cover,
        backCover = R.drawable.las_munecas_chinas_back_cover,
        spineCover = R.drawable.las_munecas_chinas_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 4
    ),
    Book(
        title = "Los Lobos Cambian el Río",
        frontCover = R.drawable.los_lobos_cambian_el_rio_front_cover,
        backCover = R.drawable.los_lobos_cambian_el_rio_back_cover,
        spineCover = R.drawable.los_lobos_cambian_el_rio_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 5
    ),
    Book(
        title = "Die and Retry",
        frontCover = R.drawable.die_and_retry_front_cover,
        backCover = R.drawable.die_and_retry_back_cover,
        spineCover = R.drawable.die_and_retry_spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    )
)
val column2Books = listOf(
    Book(
        title = "Front",
        frontCover = R.drawable.front_cover,
        backCover = R.drawable.back_cover,
        spineCover = R.drawable.spine_cover,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2000f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 4
    ),
    Book(
        title = "The Law of Human Nature",
        frontCover = R.drawable.the_law_of_human_nature_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 5
    ),
    Book(
        title = "The Mountain Is You",
        frontCover = R.drawable.the_mountain_is_you_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Picture of Dorian Gray",
        frontCover = R.drawable.the_picture_of_dorian_gray_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Without a Trace",
        frontCover = R.drawable.without_a_trace_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Think and Grow Rich",
        frontCover = R.drawable.think_and_grow_rich_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "Ganbatte!",
        frontCover = R.drawable.ganbatte_front_cover,
        backCover = R.drawable.ganbatte_back_cover,
        spineCover = R.drawable.ganbatte_spine_cover,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "Kitchen",
        frontCover = R.drawable.kitchen_front_cover,
        backCover = R.drawable.kitchen_back_cover,
        spineCover = R.drawable.kitchen_spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Las Muñecas Chinas",
        frontCover = R.drawable.las_munecas_chinas_front_cover,
        backCover = R.drawable.las_munecas_chinas_back_cover,
        spineCover = R.drawable.las_munecas_chinas_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 2
    ),
    Book(
        title = "Los Lobos Cambian el Río",
        frontCover = R.drawable.los_lobos_cambian_el_rio_front_cover,
        backCover = R.drawable.los_lobos_cambian_el_rio_back_cover,
        spineCover = R.drawable.los_lobos_cambian_el_rio_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1200f,
        controlPointX = -2000f,
        controlPointY = 100f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 1
    ),
    Book(
        title = "Die and Retry",
        frontCover = R.drawable.die_and_retry_front_cover,
        backCover = R.drawable.die_and_retry_back_cover,
        spineCover = R.drawable.die_and_retry_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -2000f,
        controlPointY = 1500f,
        controlPoint2X = 2500f,
        controlPoint2Y = -2000f,
        slot = 3
    )
)
val column3Books = listOf(
    Book(
        title = "Front",
        frontCover = R.drawable.front_cover,
        backCover = R.drawable.back_cover,
        spineCover = R.drawable.spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 4
    ),
    Book(
        title = "The Law of Human Nature",
        frontCover = R.drawable.the_law_of_human_nature_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 5
    ),
    Book(
        title = "The Mountain Is You",
        frontCover = R.drawable.the_mountain_is_you_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Picture of Dorian Gray",
        frontCover = R.drawable.the_picture_of_dorian_gray_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Without a Trace",
        frontCover = R.drawable.without_a_trace_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Think and Grow Rich",
        frontCover = R.drawable.think_and_grow_rich_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "Ganbatte!",
        frontCover = R.drawable.ganbatte_front_cover,
        backCover = R.drawable.ganbatte_back_cover,
        spineCover = R.drawable.ganbatte_spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Kitchen",
        frontCover = R.drawable.kitchen_front_cover,
        backCover = R.drawable.kitchen_back_cover,
        spineCover = R.drawable.kitchen_spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Las Muñecas Chinas",
        frontCover = R.drawable.las_munecas_chinas_front_cover,
        backCover = R.drawable.las_munecas_chinas_back_cover,
        spineCover = R.drawable.las_munecas_chinas_spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 2
    ),
    Book(
        title = "Los Lobos Cambian el Río",
        frontCover = R.drawable.los_lobos_cambian_el_rio_front_cover,
        backCover = R.drawable.los_lobos_cambian_el_rio_back_cover,
        spineCover = R.drawable.los_lobos_cambian_el_rio_spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 1
    ),
    Book(
        title = "Die and Retry",
        frontCover = R.drawable.die_and_retry_front_cover,
        backCover = R.drawable.die_and_retry_back_cover,
        spineCover = R.drawable.die_and_retry_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -2000f,
        controlPointY = 1500f,
        controlPoint2X = 2500f,
        controlPoint2Y = -2000f,
        slot = 3
    )
)

// TODO: add the remaining columns here, e.g.
// val column2Books = listOf( ... )
// val column3Books = listOf( ... )
// val column4Books = listOf( ... )