package com.example.ebook

val column1Books = listOf(
    Book(
        title = "Front",
        frontCover = R.drawable.front_cover,
        backCover = R.drawable.back_cover,
        spineCover = R.drawable.spine_cover,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Law of Human Nature",
        frontCover = R.drawable.the_law_of_human_nature_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Mountain Is You",
        frontCover = R.drawable.the_mountain_is_you_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Picture of Dorian Gray",
        frontCover = R.drawable.the_picture_of_dorian_gray_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Without a Trace",
        frontCover = R.drawable.without_a_trace_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Think and Grow Rich",
        frontCover = R.drawable.think_and_grow_rich_front_cover,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 1
    ),
    Book(
        title = "Ganbatte!",
        frontCover = R.drawable.ganbatte_front_cover,
        backCover = R.drawable.ganbatte_back_cover,
        spineCover = R.drawable.ganbatte_spine_cover,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 2
    ),
    Book(
        title = "Kitchen",
        frontCover = R.drawable.kitchen_front_cover,
        backCover = R.drawable.kitchen_back_cover,
        spineCover = R.drawable.kitchen_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 3
    ),
    Book(
        title = "Las Muñecas Chinas",
        frontCover = R.drawable.las_munecas_chinas_front_cover,
        backCover = R.drawable.las_munecas_chinas_back_cover,
        spineCover = R.drawable.las_munecas_chinas_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 4
    ),
    Book(
        title = "Los Lobos Cambian el Río",
        frontCover = R.drawable.los_lobos_cambian_el_rio_front_cover,
        backCover = R.drawable.los_lobos_cambian_el_rio_back_cover,
        spineCover = R.drawable.los_lobos_cambian_el_rio_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 5
    ),
    Book(
        title = "Die and Retry",
        frontCover = R.drawable.die_and_retry_front_cover,
        backCover = R.drawable.die_and_retry_back_cover,
        spineCover = R.drawable.die_and_retry_spine_cover,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -1500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 6
    )
)
val column2Books = listOf(
    Book(
        title = "Smashed Idols",
        frontCover = R.drawable.smashed_idols,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2000f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 6
    ),
    Book(
        title = "What Remains of Her",
        frontCover = R.drawable.what_remains_of_her,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 7
    ),
    Book(
        title = "On the Run",
        frontCover = R.drawable.on_the_run,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Things I Never Got to Tell You",
        frontCover = R.drawable.things_i_never_got_to_tell_you,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Alfred Saves the Day",
        frontCover = R.drawable.alfred_saves_the_day,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "Zodak the Last Shielder",
        frontCover = R.drawable.zodak_the_last_shielder,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "Lonely Space",
        frontCover = R.drawable.lonely_space,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "The Dazzling Magic of a Petit Four",
        frontCover = R.drawable.the_dazzling_magic_of_a_petit_four,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Death and Life of Amy Smith",
        frontCover = R.drawable.the_death_and_life_of_amy_smith,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -2500f,
        controlPointY = -400f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 2
    ),
    Book(
        title = "Nelly Finds Her Niche",
        frontCover = R.drawable.nelly_finds_her_niche,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1200f,
        controlPointX = -2500f,
        controlPointY = 100f,
        controlPoint2X = 2500f,
        controlPoint2Y = -400f,
        slot = 1
    ),
    Book(
        title = "I Will Watch from Up Here",
        frontCover = R.drawable.i_will_watch_from_up_here,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -2000f,
        controlPointY = 1500f,
        controlPoint2X = 2500f,
        controlPoint2Y = -2000f,
        slot = 3
    )
)
val column3Books = listOf(
    Book(
        title = "Farewell to Summer",
        frontCover = R.drawable.farewell_to_summer,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 4
    ),
    Book(
        title = "In the Footsteps of Baal",
        frontCover = R.drawable.in_the_footsteps_of_baal,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 5
    ),
    Book(
        title = "The Book of Jacob",
        frontCover = R.drawable.the_book_of_jacob,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "The Alchemy of Emotions",
        frontCover = R.drawable.the_alchemy_of_emotions,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 6
    ),
    Book(
        title = "After the Peter",
        frontCover = R.drawable.after_the_peter,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 7
    ),
    Book(
        title = "A Siren Song",
        frontCover = R.drawable.a_siren_song,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "Entranced",
        frontCover = R.drawable.entranced,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1200f,
        controlPointX = -2500f,
        controlPointY = 1500f,
        controlPoint2X = 2000f,
        controlPoint2Y = -1000f,
        slot = 3
    ),
    Book(
        title = "Converse",
        frontCover = R.drawable.converse,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1200f,
        controlPointX = -2500f,
        controlPointY = 1500f,
        controlPoint2X = 2000f,
        controlPoint2Y = -1000f,
        slot = 4
    ),
    Book(
        title = "Pearl Bound",
        frontCover = R.drawable.pearl_bound,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 2
    ),
    Book(
        title = "Crossing the Sea of Shattered Glass",
        frontCover = R.drawable.crossing_the_sea_of_shattered_glass,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 1
    ),
    Book(
        title = "American Apostasy",
        frontCover = R.drawable.american_apostasy,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1100f,
        controlPointX = -2000f,
        controlPointY = 1500f,
        controlPoint2X = 2500f,
        controlPoint2Y = -2000f,
        slot = 3
    )
)
val column4Books = listOf(
    Book(
        title = "Mist",
        frontCover = R.drawable.mist,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 6
    ),
    Book(
        title = "Before Tomorrow",
        frontCover = R.drawable.before_tomorrow,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 5
    ),
    Book(
        title = "An Anthropology of Wandering",
        frontCover = R.drawable.an_anthropology_of_wandering,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null
    ),
    Book(
        title = "And Never Memeory of You",
        frontCover = R.drawable.and_never_memeory_of_you,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 6
    ),
    Book(
        title = "Tom Ryan's Shows",
        frontCover = R.drawable.tom_ryans_shows,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 7
    ),
    Book(
        title = "What Keeps Us",
        frontCover = R.drawable.what_keeps_us,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1200f,
        spiralAnimationY = 1000f,
        controlPointX = 2500f,
        controlPointY = -100f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f
    ),
    Book(
        title = "Flight of the Hummingbird",
        frontCover = R.drawable.flight_of_the_hummingbird,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1200f,
        controlPointX = -2500f,
        controlPointY = 1500f,
        controlPoint2X = 2000f,
        controlPoint2Y = -1000f,
        slot = 3
    ),
    Book(
        title = "The Wilusiad",
        frontCover = R.drawable.the_wilusiad,
        backCover = null,
        spineCover = null,
        spiralAnimationX = 2000f,
        spiralAnimationY = 1200f,
        controlPointX = -2500f,
        controlPointY = 1500f,
        controlPoint2X = 2000f,
        controlPoint2Y = -1000f,
        slot = 4
    ),
    Book(
        title = "Meat",
        frontCover = R.drawable.meat,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 2
    ),
    Book(
        title = "Faith",
        frontCover = R.drawable.faith,
        backCover = null,
        spineCover = null,
        spiralAnimationX = null,
        spiralAnimationY = null,
        controlPointX = null,
        controlPointY = null,
        controlPoint2X = null,
        controlPoint2Y = null,
        slot = 1
    ),
    Book(
        title = "The Mermaid's Wrath",
        frontCover = R.drawable.the_mermaids_wrath,
        backCover = null,
        spineCover = null,
        spiralAnimationX = -1500f,
        spiralAnimationY = 1050f,
        controlPointX = 2500f,
        controlPointY = -1000f,
        controlPoint2X = 2500f,
        controlPoint2Y = 3000f,
        slot = 8
    )
)